"""Run this project end to end, and write down that it ran.


A repository whose continuous integration is frozen says nothing about itself: the green tick
is two years old, or absent. What replaces it is ``reports/run-evidence.json`` — the exact
command, the day, the revision, the tool versions, what it cost, and the tracked files it
produced. A reader can rerun that command and compare.

**The run must reproduce what the repository publishes.** The steps below regenerate the key
outputs; if any of them comes out different from the committed version, no evidence is
written and the differing files are named. That is the whole value of the exercise: evidence
that merely says « it ran » proves that something ran, not that what is published is what it
produces.

    uv run python scripts/smoke.py

Run it on a clean clone, before the release tag. No workflow writes this file: a committed
artefact regenerated by continuous integration is an artefact whose author is a machine
nobody watches.
"""

from __future__ import annotations

import json
import platform
import shutil
import subprocess
import sys
import time
from datetime import UTC, datetime
from importlib.metadata import PackageNotFoundError, version

from attrition_serving.utils.paths import ROOT_DIR, SCRIPTS_DIR

EVIDENCE = "reports/run-evidence.json"
COMMAND = "uv run python scripts/smoke.py"

#: The tracked files this run regenerates. Each one is compared with its committed version:
#: a smoke test that writes nothing proves that the process starts, not that it works.
KEY_OUTPUT: tuple[str, ...] = (
    "reports/data_quality.csv",
    "reports/cleaning_trace.csv",
    "reports/redundant_features.csv",
    "reports/feature_encoding.csv",
    "reports/univariate_tests.csv",
    "reports/evaluation_cv.csv",
    "reports/evaluation_summary.json",
    "reports/baselines.csv",
    "reports/cost_curve.csv",
    "reports/calibration.csv",
    "reports/subgroups.csv",
    "reports/pr_curves.csv",
    "reports/permutation_importance.csv",
    "reports/figures/pr_curves.png",
    "reports/figures/calibration.png",
    "reports/figures/cost_curve.png",
    "reports/figures/subgroups.png",
    "reports/figures/permutation_importance.png",
    "models/model_card.json",
    "models/expected_features.json",
)

#: The distributions whose version changes the result. Not the whole lock file — the reader
#: needs what would explain a different number, not an inventory.
TOOLS: tuple[str, ...] = ("scikit-learn", "pandas", "numpy", "scipy", "statsmodels")


#: The three commands the README's « Running it » section quotes, in that order. Written as
#: module names and not as shell strings, so the run uses the interpreter this script was
#: started with and not whatever `python` happens to mean on the PATH.
CHAIN = (
    "data_quality_report",
    "run_evaluation",
    "train_export_pipeline",
)


def steps() -> None:
    """Rebuild every published table, every figure and the served artefact, in order.

    The chain needs the extracts. Without them the first script fails where the data is
    missing, which is the right place: a smoke run that quietly skipped the data step would
    report that everything reproduces while having recomputed nothing.
    """
    import runpy

    from attrition_serving.config import PATHS

    if not (PATHS.data_raw / "extrait_sirh.csv").exists():
        raise SystemExit(
            f"no extracts under {PATHS.data_raw}. Rebuild them with "
            "`uv run python scripts/build_extracts.py --source <IBM csv>`; "
            "docs/data-source.md says what that file is."
        )

    for name in (*CHAIN, "build_figures"):
        print(f"[run] scripts/{name}.py")
        try:
            runpy.run_path(str(SCRIPTS_DIR / f"{name}.py"), run_name="__main__")
        except SystemExit as stop:
            # A script that ends on `raise SystemExit(main())` raises SystemExit(0) on
            # success, and running it under `runpy` would end this process there -- with
            # every step after it skipped and the run reported as fine.
            if stop.code:
                raise


# --- What the evidence records ----------------------------------------------


def _git(*arguments: str) -> str:
    done = subprocess.run(
        ["git", *arguments], cwd=ROOT_DIR, capture_output=True, text=True, check=False
    )
    return done.stdout.strip()


def tool_versions() -> dict[str, str]:
    versions = {"python": platform.python_version()}
    for name in TOOLS:
        try:
            versions[name] = version(name)
        except PackageNotFoundError:
            versions[name] = "not installed"
    for binary, arguments in (("uv", ("--version",)), ("docker", ("--version",))):
        if shutil.which(binary):
            done = subprocess.run([binary, *arguments], capture_output=True, text=True, check=False)
            versions[binary] = done.stdout.strip() or "unknown"
    return versions


def reproduced() -> list[str]:
    """The key outputs the run did NOT reproduce: missing, untracked, or changed."""
    problems: list[str] = []
    for rel in KEY_OUTPUT:
        if not (ROOT_DIR / rel).exists():
            problems.append(f"{rel} — not produced")
            continue
        if not _git("ls-files", "--error-unmatch", rel):
            problems.append(f"{rel} — produced but not tracked by git")
            continue
        if _git("status", "--porcelain", "--", rel):
            problems.append(f"{rel} — differs from the committed version")
    return problems


def main() -> int:
    if not KEY_OUTPUT:
        print("scripts/smoke.py: name the tracked files this run regenerates", file=sys.stderr)
        return 1

    started = time.monotonic()
    steps()
    duration = round(time.monotonic() - started, 1)

    differences = reproduced()
    if differences:
        print("the run did not reproduce what is published:", file=sys.stderr)
        for line in differences:
            print(f"  {line}", file=sys.stderr)
        print(f"{EVIDENCE} not written", file=sys.stderr)
        return 1

    evidence = {
        "command": COMMAND,
        "ran_at": datetime.now(tz=UTC).date().isoformat(),
        "git_revision": _git("rev-parse", "HEAD"),
        "tool_versions": tool_versions(),
        "duration_seconds": duration,
        "key_output": list(KEY_OUTPUT),
        # Null, and said so: the workflows of this repository are frozen to a manual trigger,
        # so there is no run to point at. A missing key would read as an oversight.
        "workflow_run_url": None,
    }
    target = ROOT_DIR / EVIDENCE
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        json.dumps(evidence, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline=""
    )
    print(f"{EVIDENCE} written — {duration}s, {len(KEY_OUTPUT)} output(s) reproduced")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
